#!/bin/bash

if [ $# -ne 3 ]; then
    echo "presto-companion Module Installer"
    echo "use: ./install_module module_path prestashop_path module_name"
    exit 1
fi

MODULE_PATH=$1
PRESTASHOP_PATH=$2
MODULE_NAME=$3

echo Install Module "$MODULE_NAME"

# Build Module Dependencies
cd $MODULE_PATH
composer update --prefer-dist --no-interaction --no-progress

# Move Module Contents to Install Folder
echo Move Module Contents to Prestashop Modules Directory

rm -Rf $PRESTASHOP_PATH/modules/$MODULE_NAME/*
cp -Rf $MODULE_PATH/*  $PRESTASHOP_PATH/modules/$1/

# Enable the Module
php bin/console prestashop:module install $MODULE_NAME

