#!/bin/bash

if [ $# -ne 1 ]; then
    echo "presto-companion PrestaShop Installer"
    echo "use: ./install prestashop_path"
    exit 1
fi

PRESTASHOP_LOCATION=$1

echo Start Prestashop located at $PRESTASHOP_LOCATION

cd $PRESTASHOP_LOCATION

composer install --prefer-dist --no-interaction --no-progress
bash travis-scripts/install-prestashop
